version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  lint-and-test:
    executor:
      name: node/default
      tag: '12.15'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: testing

  build:
    executor:
      name: node/default
      tag: '12.15'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: building
workflows:
  test_my_app:
    jobs:
      - lint-and-test
      - build:
          requires:
            - lint-and-test
